package com.yang.oa.hr.bean;

public class EmpBean {


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.UUID
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	private String uuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.EMP_NAME
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	private String empName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.EMP_CODE
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	private String empCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.POST_ID
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	private String postId;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.ORG_ID
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	private String orgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.PWD
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	private String pwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.ADDRESS
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.TEL_NUM
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	private String telNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.EMAIL
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	private String email;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.UUID
	 * @return  the value of employee.UUID
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	
	private String postName;
	public String getPostName() {
		return postName;
	}

	public void setPostName(String postName) {
		this.postName = postName;
	}

	public String getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.UUID
	 * @param uuid  the value for employee.UUID
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.EMP_NAME
	 * @return  the value of employee.EMP_NAME
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	public String getEmpName() {
		return empName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.EMP_NAME
	 * @param empName  the value for employee.EMP_NAME
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	public void setEmpName(String empName) {
		this.empName = empName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.EMP_CODE
	 * @return  the value of employee.EMP_CODE
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	public String getEmpCode() {
		return empCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.EMP_CODE
	 * @param empCode  the value for employee.EMP_CODE
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.POST_ID
	 * @return  the value of employee.POST_ID
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	public String getPostId() {
		return postId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.POST_ID
	 * @param postId  the value for employee.POST_ID
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	public void setPostId(String postId) {
		this.postId = postId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.ORG_ID
	 * @return  the value of employee.ORG_ID
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	public String getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.ORG_ID
	 * @param orgId  the value for employee.ORG_ID
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.PWD
	 * @return  the value of employee.PWD
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.PWD
	 * @param pwd  the value for employee.PWD
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.ADDRESS
	 * @return  the value of employee.ADDRESS
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.ADDRESS
	 * @param address  the value for employee.ADDRESS
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.TEL_NUM
	 * @return  the value of employee.TEL_NUM
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	public String getTelNum() {
		return telNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.TEL_NUM
	 * @param telNum  the value for employee.TEL_NUM
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	public void setTelNum(String telNum) {
		this.telNum = telNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.EMAIL
	 * @return  the value of employee.EMAIL
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.EMAIL
	 * @param email  the value for employee.EMAIL
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	public void setEmail(String email) {
		this.email = email;
	}

}
