package com.yang.oa.hr.dao;

import java.util.List;
import java.util.Map;

import com.yang.oa.commons.MyBatisRepository;
import com.yang.oa.commons.PagingBean;
import com.yang.oa.hr.entity.Employee;
@MyBatisRepository
public interface EmployeeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	int deleteByPrimaryKey(String uuid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	int insert(Employee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	int insertSelective(Employee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	Employee selectByPrimaryKey(String uuid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	int updateByPrimaryKeySelective(Employee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbggenerated  Mon May 13 20:38:51 CST 2013
	 */
	int updateByPrimaryKey(Employee record);
	List<Employee>  selectAllEmp();
	List<Employee> selectByCodeAndName(Map map);
	int selectRowNumByCodeAndName(Map map);
	List<Employee> selectByOrg(String orgId);
	List<Employee> selectEmpPageing(PagingBean pageBean);
	Employee selectByEmpCode(String empCode);
	int selectEmpsNumByOrg(String orgid);
	int selectEmpsNumByPost(String postId);
	int selectEmpNum();
	int deleteEmpBatch(List<String> empsid);
}