package com.yang.oa.hr.dao;

import java.util.List;

import com.yang.oa.commons.MyBatisRepository;
import com.yang.oa.hr.entity.Organization;
@MyBatisRepository
public interface OrganizationMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table organization
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	int deleteByPrimaryKey(String uuid);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table organization
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	int insert(Organization record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table organization
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	int insertSelective(Organization record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table organization
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	Organization selectByPrimaryKey(String uuid);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table organization
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	int updateByPrimaryKeySelective(Organization record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table organization
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	int updateByPrimaryKey(Organization record);
	List<Organization> selectParentIsNull();
    List<Organization> selectOrgByParentid(String parentid);
    int getOrgChildNum(String parentid);
    int deleteBatch(List<Organization> list);
}