package com.yang.oa.hr.dao;

import java.util.List;

import com.yang.oa.commons.MyBatisRepository;
import com.yang.oa.hr.entity.Post;
@MyBatisRepository
public interface PostMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	int deleteByPrimaryKey(String uuid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	int insert(Post record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	int insertSelective(Post record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	Post selectByPrimaryKey(String uuid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	int updateByPrimaryKeySelective(Post record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	int updateByPrimaryKey(Post record);
	int deletePostsBatch(List<Post> posts);
	
	List<Post> selectByParent(String parentid);
    int getPostChildNum(String parentid);
}