package com.yang.oa.hr.dao;

import java.util.List;

import com.yang.oa.commons.MyBatisRepository;
import com.yang.oa.hr.bean.RoleEmpBean;
import com.yang.oa.hr.entity.RoleGroup;
@MyBatisRepository
public interface RoleGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_group
     *
     * @mbggenerated Mon May 20 16:25:46 CST 2013
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_group
     *
     * @mbggenerated Mon May 20 16:25:46 CST 2013
     */
    int insert(RoleGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_group
     *
     * @mbggenerated Mon May 20 16:25:46 CST 2013
     */
    int insertSelective(RoleGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_group
     *
     * @mbggenerated Mon May 20 16:25:46 CST 2013
     */
    RoleGroup selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_group
     *
     * @mbggenerated Mon May 20 16:25:46 CST 2013
     */
    int updateByPrimaryKeySelective(RoleGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_group
     *
     * @mbggenerated Mon May 20 16:25:46 CST 2013
     */
    int updateByPrimaryKey(RoleGroup record);
    List<RoleEmpBean> selectByRoleId(String roleId);
    List<String> selectByGroupId(String groupId);
    int deleteRoleEmpBatchByRoleIds(List<String> roleIds);
    int deleteRoleEmpBatchByEmpsIds(List<String> empIds);
    int deleteRoleEmpBatchByIds(List<String> ids);
}