package com.yang.oa.hr.dao;

import java.util.List;
import java.util.Map;

import com.yang.oa.commons.MyBatisRepository;
import com.yang.oa.hr.entity.RoleRes;
@MyBatisRepository
public interface RoleResMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_res
     *
     * @mbggenerated Sun May 19 18:20:34 CST 2013
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_res
     *
     * @mbggenerated Sun May 19 18:20:34 CST 2013
     */
    int insert(RoleRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_res
     *
     * @mbggenerated Sun May 19 18:20:34 CST 2013
     */
    int insertSelective(RoleRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_res
     *
     * @mbggenerated Sun May 19 18:20:34 CST 2013
     */
    RoleRes selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_res
     *
     * @mbggenerated Sun May 19 18:20:34 CST 2013
     */
    int updateByPrimaryKeySelective(RoleRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_res
     *
     * @mbggenerated Sun May 19 18:20:34 CST 2013
     */
    int updateByPrimaryKey(RoleRes record);
    
    int deleteByRoleIdAndResId(Map<String,String> map);
    
    List<String> selectByRoleId(String roleid);
    List<String> selectByResId(String resid);
    Map<String,String> selecAllRoleUrl();
    int deleteRoleResBatchByRoleIds(List<String> rolesid);
    int deleteRoleResBatchByResIds(List<String> resIds);
}