package com.yang.oa.hr.dao;

import java.util.List;

import com.yang.oa.commons.MyBatisRepository;
import com.yang.oa.hr.entity.SysResource;
@MyBatisRepository
public interface SysResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    int insert(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    int insertSelective(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    SysResource selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    int updateByPrimaryKeySelective(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    int updateByPrimaryKey(SysResource record);
    
    List<SysResource> selectByParentid(String parentid);
    List<SysResource> selectAllPage();
    int getResChildNum(String parentid);
    int deleteResBatchByResId(List<String> ids);
}