package com.yang.oa.hr.entity;

public class Organization {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column organization.UUID
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	private String uuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column organization.ORG_NAME
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	private String orgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column organization.ORG_CODE
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	private String orgCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column organization.PARENTID
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	private String parentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column organization.ADDRESS
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column organization.ORG_LEVEL
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	private String orgLevel;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column organization.UUID
	 * @return  the value of organization.UUID
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	public String getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column organization.UUID
	 * @param uuid  the value for organization.UUID
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column organization.ORG_NAME
	 * @return  the value of organization.ORG_NAME
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	public String getOrgName() {
		return orgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column organization.ORG_NAME
	 * @param orgName  the value for organization.ORG_NAME
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column organization.ORG_CODE
	 * @return  the value of organization.ORG_CODE
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	public String getOrgCode() {
		return orgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column organization.ORG_CODE
	 * @param orgCode  the value for organization.ORG_CODE
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column organization.PARENTID
	 * @return  the value of organization.PARENTID
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	public String getParentid() {
		return parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column organization.PARENTID
	 * @param parentid  the value for organization.PARENTID
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	public void setParentid(String parentid) {
		this.parentid = parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column organization.ADDRESS
	 * @return  the value of organization.ADDRESS
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column organization.ADDRESS
	 * @param address  the value for organization.ADDRESS
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column organization.ORG_LEVEL
	 * @return  the value of organization.ORG_LEVEL
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	public String getOrgLevel() {
		return orgLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column organization.ORG_LEVEL
	 * @param orgLevel  the value for organization.ORG_LEVEL
	 * @mbggenerated  Fri May 10 15:09:04 CST 2013
	 */
	public void setOrgLevel(String orgLevel) {
		this.orgLevel = orgLevel;
	}
}