package com.yang.oa.hr.entity;

public class Post {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.UUID
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	private String uuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.POST_NAME
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	private String postName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.POST_CODE
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	private String postCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.PARENTID
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	private String parentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.POST_DIS
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	private String postDis;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.POST_LEVEL
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	private String postLevel;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.UUID
	 * @return  the value of post.UUID
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	public String getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.UUID
	 * @param uuid  the value for post.UUID
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.POST_NAME
	 * @return  the value of post.POST_NAME
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	public String getPostName() {
		return postName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.POST_NAME
	 * @param postName  the value for post.POST_NAME
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	public void setPostName(String postName) {
		this.postName = postName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.POST_CODE
	 * @return  the value of post.POST_CODE
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	public String getPostCode() {
		return postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.POST_CODE
	 * @param postCode  the value for post.POST_CODE
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.PARENTID
	 * @return  the value of post.PARENTID
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	public String getParentid() {
		return parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.PARENTID
	 * @param parentid  the value for post.PARENTID
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	public void setParentid(String parentid) {
		this.parentid = parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.POST_DIS
	 * @return  the value of post.POST_DIS
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	public String getPostDis() {
		return postDis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.POST_DIS
	 * @param postDis  the value for post.POST_DIS
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	public void setPostDis(String postDis) {
		this.postDis = postDis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.POST_LEVEL
	 * @return  the value of post.POST_LEVEL
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	public String getPostLevel() {
		return postLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.POST_LEVEL
	 * @param postLevel  the value for post.POST_LEVEL
	 * @mbggenerated  Sun May 12 13:11:51 CST 2013
	 */
	public void setPostLevel(String postLevel) {
		this.postLevel = postLevel;
	}
}