package com.yang.oa.hr.entity;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.UUID
     *
     * @mbggenerated Thu May 16 16:20:53 CST 2013
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.ROLE_NAME
     *
     * @mbggenerated Thu May 16 16:20:53 CST 2013
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.ROLE_CODE
     *
     * @mbggenerated Thu May 16 16:20:53 CST 2013
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.PARENTID
     *
     * @mbggenerated Thu May 16 16:20:53 CST 2013
     */
    private String parentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.UUID
     *
     * @return the value of role.UUID
     *
     * @mbggenerated Thu May 16 16:20:53 CST 2013
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.UUID
     *
     * @param uuid the value for role.UUID
     *
     * @mbggenerated Thu May 16 16:20:53 CST 2013
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.ROLE_NAME
     *
     * @return the value of role.ROLE_NAME
     *
     * @mbggenerated Thu May 16 16:20:53 CST 2013
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.ROLE_NAME
     *
     * @param roleName the value for role.ROLE_NAME
     *
     * @mbggenerated Thu May 16 16:20:53 CST 2013
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.ROLE_CODE
     *
     * @return the value of role.ROLE_CODE
     *
     * @mbggenerated Thu May 16 16:20:53 CST 2013
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.ROLE_CODE
     *
     * @param roleCode the value for role.ROLE_CODE
     *
     * @mbggenerated Thu May 16 16:20:53 CST 2013
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.PARENTID
     *
     * @return the value of role.PARENTID
     *
     * @mbggenerated Thu May 16 16:20:53 CST 2013
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.PARENTID
     *
     * @param parentid the value for role.PARENTID
     *
     * @mbggenerated Thu May 16 16:20:53 CST 2013
     */
    public void setParentid(String parentid) {
        this.parentid = parentid;
    }
}