package com.yang.oa.hr.entity;

public class RoleGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_group.UUID
     *
     * @mbggenerated Mon May 20 16:25:46 CST 2013
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_group.ROLEID
     *
     * @mbggenerated Mon May 20 16:25:46 CST 2013
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_group.GROUPID
     *
     * @mbggenerated Mon May 20 16:25:46 CST 2013
     */
    private String groupid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_group.UUID
     *
     * @return the value of role_group.UUID
     *
     * @mbggenerated Mon May 20 16:25:46 CST 2013
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_group.UUID
     *
     * @param uuid the value for role_group.UUID
     *
     * @mbggenerated Mon May 20 16:25:46 CST 2013
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_group.ROLEID
     *
     * @return the value of role_group.ROLEID
     *
     * @mbggenerated Mon May 20 16:25:46 CST 2013
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_group.ROLEID
     *
     * @param roleid the value for role_group.ROLEID
     *
     * @mbggenerated Mon May 20 16:25:46 CST 2013
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_group.GROUPID
     *
     * @return the value of role_group.GROUPID
     *
     * @mbggenerated Mon May 20 16:25:46 CST 2013
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_group.GROUPID
     *
     * @param groupid the value for role_group.GROUPID
     *
     * @mbggenerated Mon May 20 16:25:46 CST 2013
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }
}