package com.yang.oa.hr.entity;

public class RoleRes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_res.UUID
     *
     * @mbggenerated Sun May 19 18:20:34 CST 2013
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_res.ROLEID
     *
     * @mbggenerated Sun May 19 18:20:34 CST 2013
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_res.RESID
     *
     * @mbggenerated Sun May 19 18:20:34 CST 2013
     */
    private String resid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_res.UUID
     *
     * @return the value of role_res.UUID
     *
     * @mbggenerated Sun May 19 18:20:34 CST 2013
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_res.UUID
     *
     * @param uuid the value for role_res.UUID
     *
     * @mbggenerated Sun May 19 18:20:34 CST 2013
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_res.ROLEID
     *
     * @return the value of role_res.ROLEID
     *
     * @mbggenerated Sun May 19 18:20:34 CST 2013
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_res.ROLEID
     *
     * @param roleid the value for role_res.ROLEID
     *
     * @mbggenerated Sun May 19 18:20:34 CST 2013
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_res.RESID
     *
     * @return the value of role_res.RESID
     *
     * @mbggenerated Sun May 19 18:20:34 CST 2013
     */
    public String getResid() {
        return resid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_res.RESID
     *
     * @param resid the value for role_res.RESID
     *
     * @mbggenerated Sun May 19 18:20:34 CST 2013
     */
    public void setResid(String resid) {
        this.resid = resid;
    }
}