package com.yang.oa.hr.entity;

public class SysResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.UUID
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.RES_NAME
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    private String resName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.RES_CODE
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    private String resCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.RES_TYPE
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    private String resType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.PARENTID
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.URL_CODE
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    private String urlCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.ACTION
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.ORDER_NUM
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    private Integer orderNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.UUID
     *
     * @return the value of sys_resource.UUID
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.UUID
     *
     * @param uuid the value for sys_resource.UUID
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.RES_NAME
     *
     * @return the value of sys_resource.RES_NAME
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    public String getResName() {
        return resName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.RES_NAME
     *
     * @param resName the value for sys_resource.RES_NAME
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    public void setResName(String resName) {
        this.resName = resName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.RES_CODE
     *
     * @return the value of sys_resource.RES_CODE
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    public String getResCode() {
        return resCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.RES_CODE
     *
     * @param resCode the value for sys_resource.RES_CODE
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    public void setResCode(String resCode) {
        this.resCode = resCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.RES_TYPE
     *
     * @return the value of sys_resource.RES_TYPE
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    public String getResType() {
        return resType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.RES_TYPE
     *
     * @param resType the value for sys_resource.RES_TYPE
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    public void setResType(String resType) {
        this.resType = resType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.PARENTID
     *
     * @return the value of sys_resource.PARENTID
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.PARENTID
     *
     * @param parentid the value for sys_resource.PARENTID
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.URL_CODE
     *
     * @return the value of sys_resource.URL_CODE
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    public String getUrlCode() {
        return urlCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.URL_CODE
     *
     * @param urlCode the value for sys_resource.URL_CODE
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    public void setUrlCode(String urlCode) {
        this.urlCode = urlCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.ACTION
     *
     * @return the value of sys_resource.ACTION
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.ACTION
     *
     * @param action the value for sys_resource.ACTION
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    public void setAction(String action) {
        this.action = action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.ORDER_NUM
     *
     * @return the value of sys_resource.ORDER_NUM
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.ORDER_NUM
     *
     * @param orderNum the value for sys_resource.ORDER_NUM
     *
     * @mbggenerated Thu May 16 20:54:00 CST 2013
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }
}