package com.yang.oa.flow.entity;

public class FlowTem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_tem.UUID
     *
     * @mbggenerated Thu Jun 06 13:23:55 CST 2013
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_tem.TEMP_CODE
     *
     * @mbggenerated Thu Jun 06 13:23:55 CST 2013
     */
    private String tempCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_tem.TEMP_NAME
     *
     * @mbggenerated Thu Jun 06 13:23:55 CST 2013
     */
    private String tempName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_tem.VERSION
     *
     * @mbggenerated Thu Jun 06 13:23:55 CST 2013
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_tem.TYPE
     *
     * @mbggenerated Thu Jun 06 13:23:55 CST 2013
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_tem.UUID
     *
     * @return the value of flow_tem.UUID
     *
     * @mbggenerated Thu Jun 06 13:23:55 CST 2013
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_tem.UUID
     *
     * @param uuid the value for flow_tem.UUID
     *
     * @mbggenerated Thu Jun 06 13:23:55 CST 2013
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_tem.TEMP_CODE
     *
     * @return the value of flow_tem.TEMP_CODE
     *
     * @mbggenerated Thu Jun 06 13:23:55 CST 2013
     */
    public String getTempCode() {
        return tempCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_tem.TEMP_CODE
     *
     * @param tempCode the value for flow_tem.TEMP_CODE
     *
     * @mbggenerated Thu Jun 06 13:23:55 CST 2013
     */
    public void setTempCode(String tempCode) {
        this.tempCode = tempCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_tem.TEMP_NAME
     *
     * @return the value of flow_tem.TEMP_NAME
     *
     * @mbggenerated Thu Jun 06 13:23:55 CST 2013
     */
    public String getTempName() {
        return tempName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_tem.TEMP_NAME
     *
     * @param tempName the value for flow_tem.TEMP_NAME
     *
     * @mbggenerated Thu Jun 06 13:23:55 CST 2013
     */
    public void setTempName(String tempName) {
        this.tempName = tempName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_tem.VERSION
     *
     * @return the value of flow_tem.VERSION
     *
     * @mbggenerated Thu Jun 06 13:23:55 CST 2013
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_tem.VERSION
     *
     * @param version the value for flow_tem.VERSION
     *
     * @mbggenerated Thu Jun 06 13:23:55 CST 2013
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_tem.TYPE
     *
     * @return the value of flow_tem.TYPE
     *
     * @mbggenerated Thu Jun 06 13:23:55 CST 2013
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_tem.TYPE
     *
     * @param type the value for flow_tem.TYPE
     *
     * @mbggenerated Thu Jun 06 13:23:55 CST 2013
     */
    public void setType(String type) {
        this.type = type;
    }
}